---
## https://wiki.jenkins-ci.org/display/JENKINS/Distributed+builds
## Slave must have ssh and java installed

# copy master: /home/jenkins/.ssh/id_rsa.pub to slave
- name: create jenkins user
  user: "name={{ jenkinsslave_user }} home={{ jenkinsslave_home }} generate_ssh_key=yes"

- name: ensure ssh directory exists
  file: dest="{{ jenkinsslave_home }}/.ssh" mode=0550 state=directory owner="{{ jenkinsslave_user }}"

